### ISSUE TITLE
Add automation to push bindings docs to website

### ISSUE THREAD

**Issue by derberg** [asyncapi/bindings#251]
under https://asyncapi.com/docs/reference/ we have specification rendered and also now extensions

![Screenshot 2024-05-16 at 14 14 45](https://github.com/asyncapi/bindings/assets/6995927/6687d0a6-4bf6-493a-b7e8-e70935583aae)

We just need to add workflow like https://github.com/asyncapi/extensions-catalog/blob/master/.github/workflows/update-extensions-in-website.yml to copy over markdown files with proper names and render in website

It's not important only for visibility and discoverability of info (navingate from one place and search integration) but also all keywords used in bindings increase SEO position for asyncapi.com

**Comment by ibishal** [comment]
hey @derberg we need similar workflow like this one(https://github.com/asyncapi/extensions-catalog/blob/master/.github/workflows/update-extensions-in-website.yml ) but to be adapted for binding

**Comment by derberg** [comment]
@ibishal exactly, added it to bounty

**Comment by ibishal** [comment]
i want to work on it @derberg 

i have worked with github actions in this PR and have worked on this set of PR in asyncapi

**Comment by akshatnema** [comment]
@derberg I wish to work on this issue, under the Bounty program.

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q3`, `bounty/medium`, `bounty/coding`
First assignment to third-party contributors: [2024-06-21 00:00:00 UTC+12:00](https://time.lol/#2024-06-21T00:00:00+12:00)
End Of Life after: [2024-07-31 23:59:59 UTC-12:00](https://time.lol/#2024-07-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Third-party contributors should [coherently articulate](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2119226365) how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by derberg** [comment]
@akshatnema really? nice ❤️ 

I assign to @akshatnema that is a maintainer in AsyncAPI org, a maintainer in website. This automation is actually also website related as the automation will be pushing markdown files to website. So not much onboarding is needed

**Comment by akshatnema** [comment]
> So not much onboarding is needed

Really? But I do have certain questions with me 😅 .

What are the files you need to show them in the website? Like I don't see any `docs` folder inside this repo. So, which files have to be copied to website and in which order?

**Comment by derberg** [comment]
@akshatnema please check extensions catalog repo, there is no docs either. Get familiar with what automation does there

**Comment by derberg** [comment]
I noticed I forgot that I was suppose to wait 3 days before I publish a decision who will work on issues.

I don't have a better excuse other than "Monday". My apologies.

**Comment by akshatnema** [comment]
> @akshatnema please check extensions catalog repo, there is no docs either. Get familiar with what automation does there

Yeah, I looked in its implementations, but as per the current `bindings` repo, we don't have exclusive md files like that. Here, we actually work in a fashion of having README.md file for each service. Hence, I would prefer to have these files as `http.md`, `kafka.md` in the website docs, instead of README.md files being used directly, with subdirectories. 

<img width="697" alt="image" src="https://github.com/asyncapi/bindings/assets/76521428/d26c59e5-ade2-436b-a4e0-73a0cbf71210">

wdyt? @derberg

**Comment by akshatnema** [comment]
One of the suggestions could be to change the name of `README.md` to `index.md`, as we can't have a pathname for a doc inside website, ending with `README.md`. IMO, README files are specifically designed for github repos, and we shouldn't copy this same structure at website as well.

**Comment by derberg** [comment]
@akshatnema the automation can do whatever is needed to make it work in website. Automation can definitely rename `README.md` files to a different name that will be the same as the name of the folder they are located in. So something that here is `anypointmq/README.md` can become `anypointmq.md` in website

**Comment by akshatnema** [comment]
Hey @aeworxet,
Can you please extend the deadline of the bounty issue by 2 weeks, as I caught Dengue in the previous week?

**Comment by aeworxet** [comment]
Upon [request of the Bounty Program Participant](https://github.com/asyncapi/bindings/issues/251#issuecomment-2217977308) (@akshatnema), all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by derberg** [comment]
I'm anyway also not available starting from this Friday to next Wednesday - short holidays. So won't be able to review that time

**Comment by akshatnema** [comment]
Thanks @aeworxet 

> I'm anyway also not available starting from this Friday to next Wednesday - short holidays. So won't be able to review that time

Sure @derberg. Will keep that in mind.

**Comment by aeworxet** [comment]
@akshatnema, please provide an update to the [PR](https://github.com/asyncapi/bindings/pull/258).

**Comment by aeworxet** [comment]
@akshatnema, please provide an update to the [PR](https://github.com/asyncapi/bindings/pull/258).

**Comment by aeworxet** [comment]
@akshatnema had scheduled a call with @derberg on 2024-08-27 to clarify some final details on this Bounty Issue before merging https://github.com/asyncapi/bindings/pull/258.

**Comment by aeworxet** [comment]
Development was delayed by one day due to an emergency situation.

**Comment by aeworxet** [comment]
Due to a little emergency at the Bounty Program Participant's side (@akshatnema), all remaining target dates of the Bounty Issue's Timeline are extended by one calendar week.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-09-15](https://time.lol/#2024-09-15T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-09-15](https://time.lol/#2024-09-15T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@akshatnema, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty bindings#251`, tag `bounty`, and full URL of this Bounty Issue in the description.
