### ISSUE TITLE
for protocol headers the AMQP bindings spec should use a schema object in the message binding object

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/bindings#64]
AMQP (0.9.1) protocol headers like `userId`, `replyTo`, or `timestamp` are currently defined as fields in the [operation binding object](https://github.com/asyncapi/bindings/tree/master/amqp#operation-binding-object). 

Firstly, protocol headers are probably better captured in the message binding object than in the operation binding object.

Secondly, every message at runtime can potentially use different values for protocol headers. Therefore fields in the binding object are not the appropriate mechanism to model this. Instead, a schema object should be used: see for example the [HTTP message binding object](https://github.com/asyncapi/bindings/tree/master/http#message-binding-object).

**Comment by olvlvl** [comment]
Hi everyone,

According to [the documentation](https://www.rabbitmq.com/publishers.html#message-properties) `userId`, `replyTo`, or `timestamp` are referred as "message properties", not "protocol headers". That being said, I agree with @GeraldLoeffler. Since `userId`, `replyTo`, or `timestamp` are message properties, and as such can be different for each message, it would be correct to have them defined on AsyncAPI message bindings.

**Comment by iancooper** [comment]
@GeraldLoeffler @derberg @olvlvl 

I'll post my suggested conventions in a day or so, but I'd argue that these are not bindings, but form part of the schema for the headers on the message, and can be supported by MessageTraits if you have fixed values.

If you send it over the wire, I don't believe a binding is the place to define it. I believe the binding should be where we define configuration required by the protocol. I don't think this is configuration the protocol requires, it certainly would not be a candidate for a management API used by middleware on the protocol. 

Where the way transmit a message is configurable for a protocol, it may be appropriate to use a message binding, otherwise I'm not sure it makes sense to use the binding to describe what will of necessity be in the header's Schema object (or payload for protocols that don't support headers).

**Comment by derberg** [comment]
Hey folks, where are we with this one, anyone driving it further?
